// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Inventory struct {
	ID        int64         `json:"id"`
	PosID     sql.NullInt64 `json:"pos_id"`
	Name      string        `json:"name"`
	Quantity  int32         `json:"quantity"`
	Category  string        `json:"category"`
	Located   string        `json:"located"`
	CreatedAt time.Time     `json:"created_at"`
}
